In [2]:
import requests
import pandas as pd

In [5]:
# step1_df column names

#  temp_high
#  temp_6
#  precipitation_hours
#  rain_sum 
#  snowfall_sum
#  wind_high
#  humid_avg
#  cloud_avg


# 		transformation into step2_df

# freezing = >18hours with <32F
# cold = high <60F
# warm = what's left
# hot = >6hours with >80F

#  rain
# not rainy    0 hours, or  <2.5 mm total rain
# lightly rainy    in-between
# very rainy    >= 6 hour and >=10mm

#  snow
# data used: total snow for the day
# none        =0
# some        >0
# lots        >6"
# (unlike rain, we ignore hours)

#  windy
# maximum	> ?? mph
# maybe 8? mayb 12

#  average hourlies, then:
# dry        <30%
# medium
# humid         >60%

#  average hourly "percent cloud cover"
# clear        <=33%
# partly-cloudy    34 to 66%
# cloudy        >= 67%

# step2_df column names:

# freezing
# cold
# warm
# hot
# not_rainy
# lightly_rainy
# very_rainy
# not_snowy
# lightly_snowy
# very_snowy
# windy
# low_humidity
# medium_humidity
# high_humidity
# clear
# partly_cloudy
# cloudy

In [8]:
# initialize list of lists
dummy1 = [

    ['tom', 10], 
    ['nick', 15], 
    ['juli', 14]
]
  
# Create the pandas DataFrame
df = pd.DataFrame(dummy1, columns=[
    'time'
    'temp_high',
    'temp_6'
#      'precipitation_hours'
#      'rain_sum' 
#      'snowfall_sum'
#      'wind_high'
#      'humid_avg'
#      'cloud_avg'
])

In [9]:
df

  temp_high  temp_6
0       tom      10
1      nick      15
2      juli      14